### ISSUE TITLE
Block commercials

### ISSUE THREAD

**Issue by brandonros** [marcosrg9/YouTubeTV#24]
I want to downsample the stream into like... 128x128 frames, hash them, then compare them to frames in a recorded database of known commercials. If detected, replace the stream with black (or something).

Interested?

**Comment by brandonros** [comment]
It logged me in to just YouTube, not YoutubeTV? https://tv.youtube.com/

**Comment by marcosrg9** [comment]
Good afternoon.

When designing this application, my intention was to make a legitimate use and bring a genuine experience of the platform.

However, there is the possibility to **[install extensions](https://www.electronjs.org/docs/latest/api/extensions)**. Note that everything runs under electron, which in turn uses Blink (Chromium). So some extensions from the Chrome Web Store might work.

Regarding the login issue....
This application is not a client for the YouTube TV streaming platform, but for the interface adapted to TVs called YouTube Leanback (formerly YouTube TV).

When I talk about YouTube TV I don't mean [tv.youtube.com](https://tv.youtube.com), but [youtube.com/tv](https://youtube.com/tv).

Regards.
