### ISSUE TITLE
how to save youtube settings? 

### ISSUE THREAD

**Issue by djgerman10** [marcosrg9/YouTubeTV#35]
how to save youtube settings? because I set full screen and exit the application and the settings are not saved.

_sorry for my English, greetings from Argentina_

**Comment by marcosrg9** [comment]
Hi guys, sorry for taking so long to respond, I don't have much time due to work and studies.
This week maybe I will have some free time, I will try to get on it and I will release a new build.

I also use the translator, greetings from Spain!
