### ISSUE TITLE
App remains open in background.

### ISSUE THREAD

**Issue by RealSickAF** [marcosrg9/YouTubeTV#38]
So when i close the youtube tv app it still remains open in the background and i have to either spam end task in task manager or it bugs out controls like ctrl+f and all of the shortcuts.How can i fix this?

**Comment by marcosrg9** [comment]
Good evening.

I need more information...
On what platform and architecture are you having this problem?
I need you to explain in detail how to reproduce this bug.

**Comment by RealSickAF** [comment]
it's on windows 11, and it's really easy to reproduce, even if you close the youtube tv app, the app still remains open in the background and i have to close it manually from windows task manager.

**Comment by marcosrg9** [comment]
This morning I found the bug you indicate while doing a build of version 2.4 under linux.
It seems to affect all platforms except macOS, and I know exactly where the bug is.

During this week, when I have some time, I will try to fix it and make new builds.
